blank_issues_enabled: true
contact_links:
  - name: Feedback
    url: https://github.com/unicode-org/message-format-wg/discussions/categories/feedback
    about: Comments, suggestions and other user feedback for the MessageFormat 2.0 Technical Preview
